steps:
- name: bash
  env:
  - 'BAR=$_NUM'
  script: |
    #!/usr/bin/env bash
    if [ $BAR = 1 ]
      then exit 1
    fi

    for i in 1 2 3 4
    do
      echo "Welcome $i times"
    done

substitutions:
    _NUM: '2'

options:
    substitution_option: 'ALLOW_LOOSE'