steps:
# - name: 'e2e-runner'
#   args:
#     - 'CustomFasSyncInterval=false&StateAllocationFilter=false&LifecycleContract=true&PlayerAllocationFilter=true&PlayerTracking=true&ResetMetricsOnDelete=true&SDKGracefulTermination=true&Example=true'
#     - 'e2e-test-cluster'
#     - "${_REGISTRY}"
#   id: e2e-feature-gates-1

- name: bash
  env:
  - 'BAR=$_NUM'
  - 'FOO=$_FEATURE_WITH_GATE'
  - 'FOOFOO=$_FEATURE_WITHOUT_GATE'
  script: |
    #!/usr/bin/env bash
    echo $BAR
    if [ $BAR = generic ]
      then exit 1
    fi

    echo "Welcome $FOO"
    echo "Welcome $FOOFOO"
    for i in 1 2 3 4
    do
      sleep 20
    done
    echo "Welcome $FOOFOO"
  id: e2e-$BAR

options:
    substitution_option: 'ALLOW_LOOSE'

tags: ['e2e-test']