steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    for i in 1 2 3 4
    do
      echo "Welcome $i times"
      sleep 10
    done

substitutions:
  _FAVORITE_COLOR: yellow
options:
    substitution_option: 'ALLOW_LOOSE'