steps:
# - name: 'e2e-runner'
#   args:
#     - 'CustomFasSyncInterval=false&StateAllocationFilter=false&LifecycleContract=true&PlayerAllocationFilter=true&PlayerTracking=true&ResetMetricsOnDelete=true&SDKGracefulTermination=true&Example=true'
#     - 'e2e-test-cluster'
#     - "${_REGISTRY}"
#   id: e2e-feature-gates-1

- name: bash
  env:
  - 'BAR=$_NUM'
  script: |
    #!/usr/bin/env bash
    echo $BAR
    if [ $BAR = 1 ]
      then exit 1
    fi

    for i in 1 2 3 4
    do
      echo "Welcome $i times"
    done
  id: 'e2e-${_NUM}'

# substitutions:
#     _NUM: '2'

options:
    substitution_option: 'ALLOW_LOOSE'