steps:
  #
  # Creates the initial make + docker build platform
  #
  - name: ubuntu
    args:
      - bash
      - -c
      - "echo 'FROM gcr.io/cloud-builders/docker\nRUN apt-get install make\nENTRYPOINT\
        \ [\"/usr/bin/make\"]' > Dockerfile.build"
    waitFor: ['-']
  - name: gcr.io/cloud-builders/docker
    id: build-make-docker
    args: [build, -f, Dockerfile.build, -t, make-docker, .]  # we need docker and make to run everything.

  #
  # pull the main build image if it exists
  #
  - name: make-docker
    id: pull-build-image
    dir: build
    env: ['REGISTRY=${_REGISTRY}']
    args: [pull-build-image]
    waitFor:
      - build-make-docker

  # kick off the child e2e test cloud builds in parallel, fail this build if any of the child build fails
  - name: gcr.io/cloud-builders/gcloud
    id: submit-e2e-test-cloud-build
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        set -o pipefail
        pids=()
        gcloud container clusters get-credentials standard-e2e-test-cluster-1-27 --zone=us-east1 --project=gongmax-gke-dev
        mkdir -p /go/src/agones.dev/ /root/.kube/
        ln -s /workspace /go/src/agones.dev/agones
        cd /go/src/agones.dev/agones/build
        make test-install-yaml
        echo "all done"
    waitFor:
      - pull-build-image

substitutions:
  _REGISTRY: us-docker.pkg.dev/agones-images/ci
tags: [ci, 'commit-${COMMIT_SHA}']
timeout: 18000s  # 5h: 3h (e2e-wait-to-become-leader) + 1.5h (e2e timeout) + 0.5h (everything else)
queueTtl: 259200s  # 72h
options:
  machineType: E2_HIGHCPU_32
  dynamic_substitutions: true